export interface LevelConfig {
  month: number
  city: string
  title: string
  story: string
  emoji: string
  skyTop: string
  skyBottom: string
  groundColor: string
  groundTopColor: string
  platformColor: string
  length: number
  speed: number
  gapChance: number
  obstacleChance: number
  platformChance: number
  heartCount: number
  specialEmoji: string
}

const levels: LevelConfig[] = [
  {
    month: 1,
    city: 'Kadıköy, İstanbul',
    title: 'Tanıştık!',
    story: 'Kadıköy\'de saçma sapan bir şekilde tanıştık. Sonra Aslı\'nın evinde ilk anlamlı tanışmamız oldu. Ve her şey böyle başladı...',
    emoji: '💫',
    skyTop: '#ff7b54',
    skyBottom: '#ffb26b',
    groundColor: '#5c4033',
    groundTopColor: '#7cba5c',
    platformColor: '#8b6f47',
    length: 3500,
    speed: 1.0,
    gapChance: 0.08,
    obstacleChance: 0.1,
    platformChance: 0.15,
    heartCount: 5,
    specialEmoji: '✨',
  },
  {
    month: 2,
    city: 'Bozcaada',
    title: 'Doğum Günün Kutlu Olsun!',
    story: 'Aslı\'nın doğum günü için Bozcaada\'ya gittik. 17 Mayıs. Rüzgâr, deniz, şarap ve sen... Mükemmel bir kaçamak!',
    emoji: '🎂',
    skyTop: '#4facfe',
    skyBottom: '#00f2fe',
    groundColor: '#c2b280',
    groundTopColor: '#e8d5a3',
    platformColor: '#7b9e3a',
    length: 3800,
    speed: 1.0,
    gapChance: 0.10,
    obstacleChance: 0.12,
    platformChance: 0.18,
    heartCount: 6,
    specialEmoji: '🎂',
  },
  {
    month: 3,
    city: 'ODTÜ, Ankara',
    title: 'Kampüs Macerası',
    story: 'Beraber ODTÜ\'ye gittik! Kampüsün yeşilliklerinde kaybolmak, göl kenarında yürümek... Güzel bir gündü.',
    emoji: '🎓',
    skyTop: '#a8edea',
    skyBottom: '#fed6e3',
    groundColor: '#5a7247',
    groundTopColor: '#8fbc5a',
    platformColor: '#c9a96e',
    length: 3500,
    speed: 1.05,
    gapChance: 0.10,
    obstacleChance: 0.12,
    platformChance: 0.20,
    heartCount: 5,
    specialEmoji: '🦌',
  },
  {
    month: 4,
    city: 'İstanbul',
    title: 'Evde Güzel',
    story: 'İstanbul\'da sakin bir ay. Evde birlikte vakit geçirmek, dizi izlemek, yemek yapmak... Bir de arkadaşının nişanına gittik!',
    emoji: '🏠',
    skyTop: '#ffecd2',
    skyBottom: '#fcb69f',
    groundColor: '#6b5b4f',
    groundTopColor: '#8b7b6f',
    platformColor: '#d4a373',
    length: 3200,
    speed: 1.0,
    gapChance: 0.08,
    obstacleChance: 0.10,
    platformChance: 0.15,
    heartCount: 5,
    specialEmoji: '💍',
  },
  {
    month: 5,
    city: 'Ankara / Ağva / Fenerbahçe',
    title: 'Düğünler & Maceralar',
    story: 'Ankara\'da düğüne gittik, sonra pavyona çıktık 😂 Ağva\'da 2 gün sahilde kaldık. Bir de Fenerbahçe\'de nikâh şahidi oldum!',
    emoji: '💃',
    skyTop: '#0c0c3a',
    skyBottom: '#1a1a5e',
    groundColor: '#4a4a6a',
    groundTopColor: '#6a6a8a',
    platformColor: '#8a7acc',
    length: 4500,
    speed: 1.1,
    gapChance: 0.12,
    obstacleChance: 0.15,
    platformChance: 0.22,
    heartCount: 7,
    specialEmoji: '🎤',
  },
  {
    month: 6,
    city: 'Diyarbakır / Mardin',
    title: 'Güneydoğu Keşfi',
    story: 'Diyarbakır\'da düğüne gittik, Mardin\'i gezdik. Taş sokaklar, güneş, inanılmaz lezzetler... Güneydoğu\'yu birlikte keşfettik!',
    emoji: '🏛️',
    skyTop: '#f9a825',
    skyBottom: '#ff8f00',
    groundColor: '#a0845c',
    groundTopColor: '#c4a97a',
    platformColor: '#d4a373',
    length: 4000,
    speed: 1.1,
    gapChance: 0.12,
    obstacleChance: 0.14,
    platformChance: 0.20,
    heartCount: 6,
    specialEmoji: '☀️',
  },
  {
    month: 7,
    city: 'Balıkesir / Kaş',
    title: 'Doğum Günüm!',
    story: 'Balıkesir\'de düğün, Kaş\'ta infinity pool\'lu muhteşem bir ev! 14 Ekim — benim doğum günüm. En güzel hediye sendin.',
    emoji: '🌊',
    skyTop: '#00b4d8',
    skyBottom: '#90e0ef',
    groundColor: '#2a6f97',
    groundTopColor: '#48bfe3',
    platformColor: '#0096c7',
    length: 4200,
    speed: 1.15,
    gapChance: 0.13,
    obstacleChance: 0.15,
    platformChance: 0.22,
    heartCount: 7,
    specialEmoji: '🏊',
  },
  {
    month: 8,
    city: 'İstanbul',
    title: 'Yoğun Kasım',
    story: 'E-ticaret sektörü kasımda çıldırıyor! Ama yine de vakit bulduk: Aslı saçını kısa kestirdi 💇‍♀️ GS Ada\'da kahvaltı yaptık, arkadaşımızın bebeğini gördük.',
    emoji: '💼',
    skyTop: '#636e72',
    skyBottom: '#b2bec3',
    groundColor: '#555555',
    groundTopColor: '#777777',
    platformColor: '#ffc312',
    length: 3800,
    speed: 1.2,
    gapChance: 0.14,
    obstacleChance: 0.18,
    platformChance: 0.20,
    heartCount: 6,
    specialEmoji: '💇‍♀️',
  },
  {
    month: 9,
    city: 'İstanbul',
    title: 'Aslı Şoför Oldu!',
    story: 'Aslı araba kullanmaya başladı! Ve baya iyi kullanıyor. Artık yolculuklar daha eğlenceli 🚗',
    emoji: '🚗',
    skyTop: '#74b9ff',
    skyBottom: '#a29bfe',
    groundColor: '#444444',
    groundTopColor: '#666666',
    platformColor: '#6c5ce7',
    length: 3500,
    speed: 1.15,
    gapChance: 0.12,
    obstacleChance: 0.14,
    platformChance: 0.18,
    heartCount: 5,
    specialEmoji: '🚗',
  },
  {
    month: 10,
    city: 'Sapanca',
    title: 'Zor Ama Beraber',
    story: 'Bu ay biraz zordu. Aslı ilaçlar yüzünden bayıldı, hastaneye kaldırıldı... Ama ablası, ben, annem — hep yanındaydık. Sapanca\'da güzel bungalovlarda konakladık. Yılbaşını beraber geçirdik 🎄',
    emoji: '🏕️',
    skyTop: '#2d3436',
    skyBottom: '#636e72',
    groundColor: '#3d5c2f',
    groundTopColor: '#5a8a3c',
    platformColor: '#81a65c',
    length: 4000,
    speed: 1.1,
    gapChance: 0.12,
    obstacleChance: 0.13,
    platformChance: 0.20,
    heartCount: 8,
    specialEmoji: '🎄',
  },
  {
    month: 11,
    city: 'İstanbul',
    title: 'Hoş Geldin Leo!',
    story: 'Bu ay Leo\'yu sahiplendik! 🐾 Parvo olduğunu öğrendik, veterinere git gelli geçti ama şimdi bomba gibi. Ailemizdeki en tatlı üye.',
    emoji: '🐾',
    skyTop: '#fdcb6e',
    skyBottom: '#ffeaa7',
    groundColor: '#6b8e4e',
    groundTopColor: '#88b063',
    platformColor: '#a0522d',
    length: 3800,
    speed: 1.1,
    gapChance: 0.11,
    obstacleChance: 0.13,
    platformChance: 0.18,
    heartCount: 7,
    specialEmoji: '🐾',
  },
  {
    month: 12,
    city: 'İstanbul',
    title: 'Yeni Başlangıç',
    story: 'Yeni bir ev tuttuk! Leo artık dışarı çıkıyor. Ve... Aslı\'nın en sevdiği KFC Türkiye\'ye geldi, ilk kez birlikte gittik! 🍗 Yeni ev, yeni sayfa, aynı aşk.',
    emoji: '🏡',
    skyTop: '#fd79a8',
    skyBottom: '#fab1a0',
    groundColor: '#5c4033',
    groundTopColor: '#7cba5c',
    platformColor: '#e17055',
    length: 4500,
    speed: 1.2,
    gapChance: 0.14,
    obstacleChance: 0.16,
    platformChance: 0.22,
    heartCount: 8,
    specialEmoji: '🍗',
  },
]

export default levels
